spring.application.name=docelivery

# SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=docelivery;integratedSecurity=false;encrypt=true;trustServerCertificate=true
spring.datasource.username=SA
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.server.error.include-message=always

# Configuracoes de Conexao:
# integratedSecurity: false (usa usuario e senha do SQL)
# encrypt: true (requer criptografia)
# trustServerCertificate: true (ignora validacao de certificado SSL)

# ddl-auto:
# none: tabelas manuais
# update: atualiza tabelas conforme o model
# create: recria tabelas ao iniciar